#!python
import os, subprocess

opts = Variables([], ARGUMENTS)

# Gets the standard flags CC, CCX, etc.
Import('env')
env = env.Clone()

# Define our options
opts.Add(PathVariable('target_path', 'The path where the lib is installed.', '../../project/gdnative/'))
opts.Add(PathVariable('target_name', 'The library name.', 'libbettervehicle', PathVariable.PathAccept))

# Updates the environment with the option variables.
opts.Update(env)

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=['.'])
sources = Glob('*.cpp')

library = env.SharedLibrary(target=env['target_path'] + env['platform_path'] + env['target_name'] , source=sources)
